# create and drop tables
spring.jpa.hibernate.ddl-auto=update
 
# Oracle settings Admin@123
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=sys as sysdba
spring.datasource.password=Rohit@7600
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
server.port=8094
